### ISSUE TITLE
Improve UI Exercise window

### ISSUE THREAD

**Issue by Adito5393** [groothuisss/HIITtoget-Issues-and-Features#1]
The UI has a modern feeling and is generally intuitive, however I could see that there are 3 pages/slides with info on the Exercises window and my first reaction was to press the arrow on the right:

<img src="https://user-images.githubusercontent.com/39572144/111686064-e65f3280-8828-11eb-804f-a8108f7fe716.jpg" width="40%">

When this arrow was not working, initially I thought it is because the app is in alpha phase and it will be later implemented.

Recently we (Rosana and I) manage to figure out by trial and error that switching the pages/slides is done by swiping right/left. 🥳🥳

Could you improve the UI by making the arrows to be clickable? Or maybe just a visual hint that the slides/pages are swipe-able.

**Comment by groothuisss** [comment]
Thanks for the comment, good idea! Implemented a "swipe" icon on the bottom of the page to make clear there is more to set up. Currently building and uploading a new release, which also includes colors to show in which interval the training currently is.
