### ISSUE TITLE
PRO version not active without Internet connection after >~24h

### ISSUE THREAD

**Issue by Adito5393** [groothuisss/HIITtoget-Issues-and-Features#4]
After not using the app for a couple of days, I went to do a HIIT session and got the warning that the app is in free version meaning that all previous sessions will be deleted if I choose to continue:

<img src="https://user-images.githubusercontent.com/39572144/115114537-3815ec80-9f90-11eb-980e-a1fef677c9e2.jpg" width="45%"> <img src="https://user-images.githubusercontent.com/39572144/115114772-4b758780-9f91-11eb-8b48-0f7f3e9ca36f.jpg" width="45%">

Luckily, I could connect to Internet and restart the app to get the Pro version working again. 

I have manage to reproduce it. How to reproduce the problem:

1. Close the app, also from the recent apps window
2. Do not open for aprox 24h
3. Turn wifi and 3/4g off
4. Open app - > check about - > free version
5. Start a new exercise and you get a warning that all previous sessions will be deleted because it's a free version. 

At the moment this small inconvenience can be avoided if one opens the app (with Internet connection) in the same day of doing the exercise.  

Is it normal behaviour? It is a pitty to loose all your sessions if one forgets to connect to the Internet before going for exercising and has no way to connect to the Internet.

**Comment by groothuisss** [comment]
Thanks for reporting this issue. It is partly expected behavior. :) An online verification is done to see if a user is indeed entitled to the pro features. However, if it fails there should be a big message saying that it couldn't verify the pro status, which I notice is not showing. I will look into that and fix it with an update!

**Comment by groothuisss** [comment]
This should work again, so closing this issue for now. If there are further problems, let me know!
